FROM quay.io/ebigxa/galaxy-init:v18.05


LABEL Description="Elixir IS on running Galaxy variant calling pipelines on microservices"
LABEL software="Galaxy Init"
LABEL software.version="18.05"
LABEL version="0.1"

RUN virtualenv venv-workflow && \
    /bin/bash -c "source venv-workflow/bin/activate && \
                  pip install 'pip>=8.1' && \
                  pip install urllib3[secure] && \
                  pip install ephemeris==0.9.0 && \
                  deactivate && \
                  virtualenv --relocatable venv-workflow"

COPY \
  config/job_conf.xml \
  config/tool_conf.xml \
  config/container_resolvers_conf.xml \
  config/sanitize_whitelist.txt \
  config/tool_data_table_conf.xml \
  config/

COPY tools tools
COPY tool-data tool-data

# Reqs/limits
COPY \
  config/job_resource_params_conf.xml \
  config/phenomenal_tools2container.yaml \
  config/
COPY rules/k8s_destinations.py /galaxy-central/lib/galaxy/jobs/rules/k8s_destination.py

COPY workflows workflows_to_load
COPY post-start-actions.sh post-start-actions.sh
RUN chmod u+x post-start-actions.sh
