global:
  docker_repo:
  max_pod_retrials: 3
assignment:
- tools_id:
   - bwa_mem
  docker_repo_override: docker.io
  docker_owner_override: biocontainers
  docker_image_override: bwa
  docker_tag_override: 0.7.15

- tools_id:
   - fastqc
  docker_repo_override: docker.io
  docker_owner_override: biocontainers
  docker_image_override: fastqc
  docker_tag_override: v0.11.5

- tools_id:
   - freebayes
  docker_repo_override: quay.io
  docker_owner_override: biocontainers
  docker_image_override: freebayes
  docker_tag_override: 1.2.0--py37h56106d0_4
